#!/usr/bin/env bash
# setup-nuget-cache.sh — Set up NuGet package cache on the Pi 5 host.
#
# Creates /opt/runner-cache/nuget with correct ownership and configures the
# runner systemd service so that NUGET_PACKAGES is set in the
# runner process environment.  The inject-cache-mounts.sh hook wrapper
# then bind-mounts the directory into every job container.
#
# Usage: sudo ./setup-nuget-cache.sh [--with-local-feed]
#
# Options:
#   --with-local-feed   Also start a local BaGet NuGet mirror on
#                       localhost:${BAGET_PORT} (default 5000).  The
#                       mirror transparently proxies nuget.org and caches
#                       packages on the Pi, reducing external traffic.
#
# Environment variables (override defaults as needed):
#   NUGET_CACHE_DIR   Host path for the NuGet package cache   (default: /opt/runner-cache/nuget)
#   RUNNER_USER       System user that owns the cache          (default: actions-runner)
#   BAGET_IMAGE       Docker image for the BaGet mirror        (default: bagetter/bagetter:latest)
#   BAGET_PORT        Host port for the BaGet mirror           (default: 5000)
#   BAGET_DATA_DIR    Host path for BaGet data/db              (default: /opt/runner-cache/baget)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/runner-service.sh"

# ── Configuration ─────────────────────────────────────────────────────────
NUGET_CACHE_DIR="${NUGET_CACHE_DIR:-/opt/runner-cache/nuget}"
RUNNER_USER="${RUNNER_USER:-actions-runner}"

WITH_LOCAL_FEED=false

# BaGet image — pin to a specific digest in production for reproducibility.
# Check https://hub.docker.com/r/bagetter/bagetter/tags for current releases.
BAGET_IMAGE="${BAGET_IMAGE:-bagetter/bagetter:latest}"
BAGET_PORT="${BAGET_PORT:-5000}"
BAGET_DATA_DIR="${BAGET_DATA_DIR:-/opt/runner-cache/baget}"

# ── Argument parsing ───────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --with-local-feed) WITH_LOCAL_FEED=true ;;
    *) echo "ERROR: Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# ── Root check ─────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: This script must be run as root (use sudo)." >&2
  exit 1
fi

echo "==> Setting up NuGet package cache..."

# ── 1. Create cache directory ──────────────────────────────────────────────
if [ ! -d "$NUGET_CACHE_DIR" ]; then
  echo "  Creating $NUGET_CACHE_DIR"
  mkdir -p "$NUGET_CACHE_DIR"
else
  echo "  $NUGET_CACHE_DIR already exists — skipping creation"
fi

echo "  Ownership: ${NUGET_CACHE_DIR} → ${RUNNER_USER}"
chown -R "${RUNNER_USER}:${RUNNER_USER}" "$NUGET_CACHE_DIR"
chmod 1777 "$NUGET_CACHE_DIR"

# ── 2. Systemd drop-in: expose NUGET_PACKAGES to the runner process ────────
DROP_IN="$(runner_detect_drop_in_dir)/10-nuget-cache.conf"
DROP_IN_CONTENT=$(cat <<EOF
# Generated by setup-nuget-cache.sh — do not edit manually.
[Service]
Environment="NUGET_PACKAGES=${NUGET_CACHE_DIR}"
EOF
)

echo "  Writing systemd drop-in: $DROP_IN"
runner_write_drop_in "10-nuget-cache.conf" "$DROP_IN_CONTENT"
systemctl daemon-reload
echo "  daemon-reload done"

# ── 3. /etc/profile.d snippet for interactive shell sessions ───────────────
PROFILE_SCRIPT="/etc/profile.d/nuget-cache.sh"
if [ ! -f "$PROFILE_SCRIPT" ]; then
  echo "  Writing $PROFILE_SCRIPT"
  cat > "$PROFILE_SCRIPT" <<EOF
# NuGet package cache — written by setup-nuget-cache.sh
export NUGET_PACKAGES="${NUGET_CACHE_DIR}"
EOF
else
  echo "  $PROFILE_SCRIPT already exists — skipping"
fi

# ── 4. Optional: local BaGet NuGet feed ───────────────────────────────────
if [ "$WITH_LOCAL_FEED" = true ]; then
  echo ""
  echo "==> Setting up local BaGet NuGet feed on port ${BAGET_PORT}..."

  if ! systemctl is-active --quiet docker; then
    echo "  ERROR: Docker is not running. Run the Docker setup script first." >&2
    exit 1
  fi

  # Create data directories
  for dir in "${BAGET_DATA_DIR}/packages" "${BAGET_DATA_DIR}/db"; do
    if [ ! -d "$dir" ]; then
      echo "  Creating $dir"
      mkdir -p "$dir"
    fi
  done
  chown -R "${RUNNER_USER}:${RUNNER_USER}" "$BAGET_DATA_DIR"

  # Write BaGet appsettings.json (transparent proxy + local filesystem store)
  BAGET_CONFIG="${BAGET_DATA_DIR}/appsettings.json"
  if [ ! -f "$BAGET_CONFIG" ]; then
    echo "  Writing BaGet configuration: $BAGET_CONFIG"
    cat > "$BAGET_CONFIG" <<'EOF'
{
  "ApiKey": "local-pi-runner-key",
  "Storage": {
    "Type": "FileSystem",
    "Path": "/app/packages"
  },
  "Database": {
    "Type": "Sqlite",
    "ConnectionString": "Data Source=/app/db/bagetter.db"
  },
  "Mirror": {
    "Enabled": true,
    "PackageSource": "https://api.nuget.org/v3/index.json"
  },
  "AllowPackageOverrides": false,
  "Urls": "http://0.0.0.0:8080"
}
EOF
  else
    echo "  BaGet config already exists — skipping"
  fi

  # Pull image if not already cached
  if ! docker image inspect "$BAGET_IMAGE" >/dev/null 2>&1; then
    echo "  Pulling ${BAGET_IMAGE}..."
    docker pull "$BAGET_IMAGE"
  else
    echo "  ${BAGET_IMAGE} already cached — skipping pull"
  fi

  # Create systemd service for BaGet
  BAGET_SERVICE="/etc/systemd/system/baget.service"
  if [ ! -f "$BAGET_SERVICE" ]; then
    echo "  Creating systemd service: $BAGET_SERVICE"
    cat > "$BAGET_SERVICE" <<EOF
[Unit]
Description=BaGet local NuGet mirror
Documentation=https://www.bagetter.com/
After=docker.service
Requires=docker.service

[Service]
Restart=always
RestartSec=5
ExecStartPre=-/usr/bin/docker rm -f baget
ExecStart=/usr/bin/docker run --rm \\
  --name baget \\
  --platform linux/arm64 \\
  -p 127.0.0.1:${BAGET_PORT}:8080 \\
  -v ${BAGET_DATA_DIR}/appsettings.json:/app/appsettings.json:ro \\
  -v ${BAGET_DATA_DIR}/packages:/app/packages \\
  -v ${BAGET_DATA_DIR}/db:/app/db \\
  ${BAGET_IMAGE}
ExecStop=/usr/bin/docker stop baget

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable baget
    systemctl start baget
    echo "  BaGet started."
    echo "  Feed URL: http://localhost:${BAGET_PORT}/v3/index.json"
    echo ""
    echo "  To add the local feed to a project:"
    echo "    dotnet nuget add source http://localhost:${BAGET_PORT}/v3/index.json --name LocalPi"
  else
    echo "  BaGet service already configured — skipping"
  fi
fi

echo ""
echo "==> NuGet cache setup complete."
echo "    Cache directory : ${NUGET_CACHE_DIR}"
echo "    Systemd drop-in : ${DROP_IN}"
[ "$WITH_LOCAL_FEED" = true ] && echo "    Local NuGet feed: http://localhost:${BAGET_PORT}/v3/index.json"
echo ""
echo "  NOTE: Run inject-cache-mounts.sh to bind-mount this directory into"
echo "        job containers at /root/.nuget/packages."
