---
- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication\s+'
    line: 'PasswordAuthentication no'
    validate: "{{ common_sshd_validate_command }}"
  notify: Restart sshd

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin\s+'
    line: 'PermitRootLogin no'
    validate: "{{ common_sshd_validate_command }}"
  notify: Restart sshd
